export interface Logging {
        loggingDbid: number;
        proportioningDbid: number;
        c3DesiredCrankPosition: number | null;
        c3DesiredSlidePosition: number | null;
        c3Knockers: Uint8Array;
        c3Vibrators: Uint8Array;
        c1DesiredFlow: number | null;
        c1SlideOpening: number | null;
        c1SlideOscillation: number | null;
        c1ExpectedFlow: number | null;
        c1OscillationSpeed: number | null;
        c1Productactivationfactor: number | null;
        c1Productactivationcycletime: number | null;
        c1PlvKnocker: Uint8Array;
        c1Outputenabled: Uint8Array;
        c1Newdatarequired: Uint8Array;
        c1Done: Uint8Array;
        csSlideOpening: number | null;
        csSlideOscillation: number | null;
        csOscillationSpeed: number | null;
        csProductactivationfactor: number | null;
        csProductactivationcycletime: number | null;
        csFillingstage: number | null;
        csPlvKnocker: Uint8Array;
        csMaxflowreached: Uint8Array;
        csStuffingdone: Uint8Array;
        d2eSlideOpening: number | null;
        d2eSlideOscillation: number | null;
        d2eExpectedFlow: number | null;
        d2eOscillationSpeed: number | null;
        d2eProductactivationfactor: number | null;
        d2eProductactivationcycletime: number | null;
        d2eD2eStage: number | null;
        d2ePlvKnocker: Uint8Array;
        d2eDone: Uint8Array;
        ifTypeofdosing: number | null;
        ifNetWeight1: number | null;
        ifNetWeight2: number | null;
        ifNetWeight3: number | null;
        ifNetWeight4: number | null;
        ifNetWeight5: number | null;
        ifNetWeight6: number | null;
        ifNetWeight7: number | null;
        ifNetWeight8: number | null;
        ifNetWeight9: number | null;
        ifNetWeight10: number | null;
        ifNetWeight11: number | null;
        ifSetpoint: number | null;
        ifAccuracy: number | null;
        ifDosedWeight: number | null;
        ifDosedTime1: number | null;
        ifDosedTime2: number | null;
        ifDosedTime3: number | null;
        ifDosedTime4: number | null;
        ifDosedTime5: number | null;
        ifDosedTime6: number | null;
        ifDosedTime7: number | null;
        ifTareweight: number | null;
        ifStandstillEp: number | null;
        ifStandstillFlow: number | null;
        ifDosingActive: Uint8Array;
        ifSameproduct: Uint8Array;
        ifStandstill: Uint8Array;
        fFilteredWeight1: number | null;
        fFilteredWeight2: number | null;
        fFilteredWeight3: number | null;
        fFilteredWeight4: number | null;
        fFilteredWeight5: number | null;
        fFilteredWeight6: number | null;
        fFilteredWeight7: number | null;
        fFilteredWeight8: number | null;
        fFilteredWeight9: number | null;
        fFilteredWeight10: number | null;
        fFilteredWeight11: number | null;
        fFlow1: number | null;
        fFlow2: number | null;
        fFlow3: number | null;
        fFlow4: number | null;
        fFlow5: number | null;
        fFlow6: number | null;
        fFlow7: number | null;
        fFlow8: number | null;
        fFlow9: number | null;
        fFlow10: number | null;
        fFlow11: number | null;
        plantLoadcell: number | null;
        plantTemperature: number | null;
        plantMoisture: number | null;
        plantActualTorque: number | null;
        plantCrankPosition: number | null;
        plantSlidePosition: number | null;
}